version: '3.9'

services:

  discovery-service:
    image: discovery-service-img
    build: ./discovery
    container_name: discovery-container
    ports:
      - "8761:8761"

  postgres:
    image: postgres
    container_name: postgres_claim
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: junglediff_claims
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  gateway-service:
    image: gateway-service-img
    ports:
      - "8222:8222"
    container_name: gateway-container

  Claims:
    image: claims-service-img
    build: ./claims
    ports:
      - "8070:8070"
    container_name: claims
    depends_on:
      - discovery-service

