# Use root/example as user/password credentials
version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27018:27017
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: noswear
      MONGO_INITDB_ROOT_PASSWORD: 12345
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: noswear
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_SERVER: mongodb
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
