#start Discovery config
eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
# end Discovery config

#start service config
server:
  port: 8075
spring:
  application:
    name: articles #this name will be displated on the eureka interface (our discovery service)
  zipkin:
     base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/junglediff_articles
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: junglediff-client
            redirect-uri: http://localhost:8222/login/oauth2/code/keycloak
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Junglediff
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Junglediff

keycloak:
  realm: Junglediff
  auth-server-url: http://localhost:8080/auth
  use-resource-role-mappings: true
  bearer-only: true
  resource: junglediff-client

