# Start Discovery config
eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
# End Discovery config

# Start service config
server:
  port: 8071
spring:
  application:
    name: carpooling # This name will be displayed on the Eureka interface (our discovery service)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/junglediff_carpooling?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: degla

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


# End service config
