#start Discovery config
eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
# end Discovery config

#start service config
server:
  port: 8070
spring:
  application:
    name: claims #this name will be displated on the eureka interface (our discovery service)

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/junglediff_claims
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
