eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: claims
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/claims/**
        - id: movingServices
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/demands/**, /api/v1/movingOffers/**
        - id: feedbacks
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/Review/**, /api/v1/Rating/**
        - id: articles
          uri: http://localhost:8075
          predicates:
            - Path=/api/v1/articles/**
        - id: notification
          uri: http://localhost:8076
          predicates:
            - Path=/api/v1/notification/**
