eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: claims
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/claims/**
