#start Discovery config
eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
# end Discovery config

#start service config
server:
  port: 8050
spring:
  application:
    name: movingServices #this name will be displated on the eureka interface (our discovery service)
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: junglediff_movingServices
      port: 27017
      host: localhost